### ISSUE TITLE
ModuleNoteFound Error

### ISSUE THREAD

**Issue by DRAGONFALCON** [JonathanSourdough/Warframe-Market-Overlay#3]
Attempted to use this overlay, followed the steps. Two main issues. 

1. In the imagemethodcalc.py file I modified and uncommented this (is this correct? slashes?): 
``pytesseract.pytesseract.tesseract_cmd = cwd + "C:/Program Files/Tesseract-OCR-V5/tesseract.exe"``

2. When trying to run the overlay I get the following:
``C:\..\>python overlay.py
Traceback (most recent call last):
  File "overlay.py", line 10, in <module>
    from system_hotkey import SystemHotkey
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\system_hotkey\__init__.py", line 1, in <module>
    from system_hotkey.system_hotkey import *
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\system_hotkey\system_hotkey.py", line 22, in <module>
    import win32con
ModuleNotFoundError: No module named 'win32con'``

Not sure what to do to fix it?

**Comment by JonathanSourdough** [comment]
Hello, sorry about the problem, would you please try and type into command prompt:
`pip install pywin32`

And then try and run the overlay again. 

Also cwd is Current Working Directory. So you would want to take that out if you are giving the program the full path to tesseract.
So it should be: 
`pytesseract.pytesseract.tesseract_cmd = "C:/Program Files/Tesseract-OCR-V5/tesseract.exe"`

**Comment by zopets** [comment]
I can't understand the problem, if you know what the problem is, tell me. I will be grateful

```
C:\Warframe-Market-Overlay-master>python overlay.py
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 576, in _handle_results
    task = get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() takes 1 positional argument but 2 were given
```

![warn](https://user-images.githubusercontent.com/69974412/90779513-978b0200-e306-11ea-9467-c1a6a0ebc434.png)

**Comment by JonathanSourdough** [comment]
Hi, its likely that this is caused by either not having installed
tesseract, or you did not place it in the Path variable.

Download an installer from here: (the latest alpha should be fine)
https://digi.bib.uni-mannheim.de/tesseract/?C=M;O=D

Here is a guide on adding something to the Path Variable:
https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/
